### ISSUE TITLE
Instellingen onthouden

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#13]
De App lijkt instellingen nog niet te onthouden, waardoor je na app op nieuw op te starten opnieuwe moet inloggen.
Ook hunter naam, map type, icon nr. lijkt hij niet te onthouden.

**Comment by Dingenis** [comment]
Dit heeft te maken met het fixen van de crash. De gegevens en instellingen worden bij het opstarten verwijderd, dit gebeurt niet meer in de nieuwe versie.
