### ISSUE TITLE
Tutorial #1 - Skip

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#15]
Ik mis een knop "SKIP" bij de 2e tutorial bij de map uitleg.

**Comment by Dingenis** [comment]
De tutorial zal maar een keer worden afgespeeld, namelijk de eerste keer dat de gebruiker de app opstart. Maar dankzij #13 wordt de tutorial meedere keren afgespeeld, dit is gefixt in de opkomende release. De tutorial speelt maar een keer af, en de tutorial zelf is belangerijk en mag daarom niet geskipt worden.
