### ISSUE TITLE
Tutorial #2 - Uitleg slecht te lezen

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#16]
De uitleg bij de 2e tutorial (map) is slecht te lezen, tekst verdwijnt onder aan de pagina.

Oplossingen:
Tekst kleiner maken.
Tekst box meer ruimte naar rechts geven.

**Comment by Dingenis** [comment]
De text stond op dezelfde font size als de titel, vanaf Japp 1.7 zal de text eerder op het scherm blijven.
