### ISSUE TITLE
Map update

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#17]
Map update niet van zelf na het invoeren van een vossen spot.
Dit zou meteen moeten kunnen na het invoeren van een spot/hunt, dan kun je princiep een update forceren, of hij zou hem binnen moeten krijgen via FCM dat die moet updaten maar dat deed die dus niet..
(of FCM is stuk ;) )

**Comment by Dingenis** [comment]
Gerelateerd tot #22
