### ISSUE TITLE
Eigen tail in de app

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#18]
Ik zie in de app nog een tail van me zelf die hij via de API binnen krijgt.
Dacht dat je geen eigen tail via de API binnen moest krijgen maar dat er een client side, tail gemaakt wordt die nauwkeuriger is dan die van de API, 
API tail van toch voor om andere hunters te zien?

**Comment by Dingenis** [comment]
Aan client side moet de tail worden gemaakt, dat werd nog niet gedaan. In Japp 1.7 zal je eigen tail aan client side worden gemaakt.
