### ISSUE TITLE
GOED BEZIG!!!

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#20]
Ondanks mij vele "Issue" puntjes die ik net aangemaakt heb, heb ik het idee dat we er bijna zijn!!!
maw. HEREN GOED BEZIG!!!!

Srry moest ook ff gezegd worden ;)

**Comment by Dingenis** [comment]
Ik had precies hetzelfde idee!!! :D :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by njittam** [comment]
Inderdaad goed bezig!!
