### ISSUE TITLE
App update niet na dat er een nieuwe coord in gevoerd is vanaf de PC.

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#22]
Na het invoeren van een coord op de website, zie ik wel bijna direct een popupje dat hij vos_b aan het updaten is maar vervolgens zie ik geen verandering op de kaart.
FCM werkt dus alleen de update niet ;).

Denk dat je auto update uit hebt staan momenteel?
Aangezien die helemaal niet update op dit moment, dus hij zou de update via FCM moeten krijgen maar dat doet dus niets.

Handmatige update werkt trouwens wel rechts boven in.

**Comment by Dingenis** [comment]
Een switch op de verkeerde variabel: op het update type ipv de actie. Zal werken in de volgende versie van Japp 1.7.1. In commint 12a5f2dd5c6ab290150c062fb7780257ba8adc7c gefixt
