### ISSUE TITLE
Hunter Locatie Versturen

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#25]
Hunter locaties lijken niet meer gestuurd te worden als het scherm van de mobiel uit is.
Lijkt ook niet te updaten als de app op de achtergrond draait.

**Comment by Dingenis** [comment]
Verkeerde omzetting van float naar int(weer het gebruik van int bits), in Japp 1.7.1 zal dit gefixt zijn. Kijk commit ae898576aff34f8d16f0f8e0b6f4d892cd8914f5 voor meer details
