### ISSUE TITLE
Eigen tail via API

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#26]
Ik krijg mn eigen tail nog binnen via de API.

Wellicht gebruik je de verkeerde API aanroep voor hunter tails?

-------------------------------------------------------------------------------------------------------

### Tail hunter locaties ophalen  (iedereen behalve de aangegeven gebruiker (ANDERE):  
(Tail van max 60 min oud!!!, en max 60 coords per hunter)

HTTP METHOD: GET
URL: /hunter/SLEUTEL/andere/{hunter}
CONTENT: -
RESPONSE: 
```
{
“<naam1>”: [
	{
		“datetime”: 	“<YYYY-MM-DD HH:MM:SS>”,
		“hunter”:	“<naam>”,
		“id”:		“<id>”,
		“latitude”:	“<b.v. 52.000000>”,
“longitude”: 	“<b.v. 6.000000>”,
“icon”:		“<id>”
},
	{
		“datetime”: 	“<YYYY-MM-DD HH:MM:SS>”,
		“hunter”:	“<naam>”,
		“id”:		“<id>”,
		“latitude”:	“<b.v. 52.000000>”,
“longitude”: 	“<b.v. 6.000000>”,
“icon”:		“<id>”
}
],
	“<naam2>”: [
		{
		“datetime”: 	“<YYYY-MM-DD HH:MM:SS>”,
		“hunter”:	“<naam>”,
		“id”:		“<id>”,
		“latitude”:	“<b.v. 52.000000>”,
“longitude”: 	“<b.v. 6.000000>”,
“icon”:		“<id>”
},
		{
		“datetime”: 	“<YYYY-MM-DD HH:MM:SS>”,
		“hunter”:	“<naam>”,
		“id”:		“<id>”,
		“latitude”:	“<b.v. 52.000000>”,
“longitude”: 	“<b.v. 6.000000>”,
“icon”:		“<id>”
}
]
}
```

**Comment by Dingenis** [comment]
Dit zou al moeten werken, ik kan twee dingen bedenken

- Je hebt de Japp nog niet die dat geïmplementeerd heeft. 
-  Je kan maar een naam meegeven aan de API, en als je net gewisselt bent van Account naam naar Hunt naam. Zal hij de nieuwe Hunt naam meegeven, maar er bestaat nog entries in de db met de oude Account naam. Die zullen dus niet gefilterd worden.

**Comment by Area348** [comment]
Dan hoop ik dat het antwoord 1 is, aangezien ik me zelf zie updaten achter me. wat inhoud dat hij de huidige hunternaam gebruikt waar ik op dat moment mee rond rij.

**Comment by Area348** [comment]
Van wat ik zie is dit nu iig opgelost. Goe bezig. Hij pakte de gebruikersnaam ook al had ik inmiddels een hunternaam.
