### ISSUE TITLE
Logout/change user.

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#29]
Ik mis een logout/change user optie^^

Na installeren laatste versie wou ik met eigen account in loggen ipv. test.
Maar hij logde al weer in als test... _(ja data weg gooien is de optie voor nu ;)_

**Comment by Dingenis** [comment]
In Japp 1.7.3 zal er een uitlog knop zijn. In commit 0790b69f28189dcf25126c7c8ff51a426574c417 is de logout toegevoed.
