### ISSUE TITLE
Back Button

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#30]
Back Button op de mob, die van het menu naar de kaart terug brengt, ipv. android.

**Comment by Dingenis** [comment]
In Japp 1.7.3 zal er een backstack zijn, je kunt dus terug gaan door je geschiedenis van wisselen tussen pagina's. In de commit 10ad89c5b8a3e88cab8f04adf8f2015aaad287f6 kan je de verandering bekijken.
