### ISSUE TITLE
FCM - Gebied komt nog niet binnen

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#31]
Ik zie nog geen FCM gebieds message binnen komen.

**Comment by Dingenis** [comment]
De topics zijn hoofdletter gevoelig hoe gebruik jij ze? Ik gebruik ze zonder hoofdletter misschien gaat het daar fout.

**Comment by Dingenis** [comment]
Sorry mijn fout! Het moet `"to" : "/topics/alpha"` zijn, er moet nog een "/" voor de topics. Ik heb het aangepast in de docs :)

**Comment by Area348** [comment]
Werkt! TNX
