### ISSUE TITLE
FCM - Popup

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#32]
FCM geeft een mooie popup om te lezen in de app zelf, maar als je de app op de achtergrond hebt draaien, zie je alleen de notificatie boven in, is het mogelijk dat als je daar op klikt je in de app, de zelfde mooie popup eerst weer krijgt, om dan de message eens goed te lezen?

**Comment by Dingenis** [comment]
In Japp 1.7.3 zal de popup verschijnen als je op de notificatie hebt gedrukt. In commit 10f044d9154fed70f4036b98be60c632bab192fa kun je de wijzigingen bekijken
