### ISSUE TITLE
FCM - Popup deel 2.

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#33]
FCM geeft geen popup weer als je de app op de achtergrond hebt draaien, en vervolgens Japp weer opend via de "app-snelkoppeling" of via "recente apps".
De notificatie blijft dan wel boven in de notificatie balk staan.

**Comment by Dingenis** [comment]
Helaas kan dit niet, omdat het systeem de notificatie aanmaakt heeft de app geen idee of er een bericht is geweest terwijl hij op de background runde.
