### ISSUE TITLE
FCM - Notificatie sound.

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#34]
Is het mogelijk om een notificatie geluidje te laten horen bij een melding?
De wel bekende plink, plong, ding, of wat mensen zelf ook maar in gesteld hebben staan :p

**Comment by Dingenis** [comment]
Dit is mogelijk! Onder de "notification" moet de attributie `"sound" : "{sound}"` waar {sound} een audio bestand is die de app heeft. [Hier ](https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support)kun je de FCM pagina zien.

**Comment by Area348** [comment]
**Toegevoegd aan notification:** 
```
"notification" : {
      		"body"	: "{body}",
      	"title"	: "{title}",
      	"icon" 	: "{icon}",
"sound"	: "{sound}"
},
```

**FCM - Documentatie:**
_Sound:
Ik heb een aantal sound files (mp3) in drive gezet, hier kunnen we dan uit kiezen welke we willen gebruiken. Files komen van “notificationsounds.com” een ‘free’ sound file site af.

Meer toevoegen is mogelijk ;).
Huidige files:
all-eyes-on-me.mp3
echoed-ding.mp3
filling-your-inbox.mp3
good-morning.mp3
here-i-am.mp3
of-finally.mp3
oringz-w447.mp3
pull-back.mp3
the-calling.mp3
tweet.mp3

Als ik het goed begrepen heb kan ik via sound zelf aangeven welke van deze bestanden er afgespeeld wordt._

**Comment by Dingenis** [comment]
Ik zal binnenkort even de geluiden in de app gaan zetten. Ik had ook nog wat dingen gevonden die misschien leuk zijn voor bij het thema

- [oriental riff](https://soundcloud.com/originofpieces/oriental-riff)
- [oriental riff](https://soundcloud.com/bombaybucc/oriental-riff-1)
- [pokemon soundeffects](https://www.youtube.com/watch?v=EQEVCar9T1I)
- [pokemon] (https://www.youtube.com/watch?v=5JgxJjF7CAY) vooral de eerste hier van lijkt me erg leuk voor een notificatie geluid 
- [pokemon theme song] (https://www.youtube.com/watch?v=JuYeHPFR3f0) 
- [shaco the tank engine](https://www.youtube.com/watch?v=vjVQGw5EIPc) speciaal voor david

**Comment by Area348** [comment]
Zonder gehoord te hebben ben ik voor.
Laat maar weten welke ik moet mee sturen in de call.

**Comment by Dingenis** [comment]
Ik heb de geluiden van hierboven in mp3 formaat gekregen, maar ik kan ze niet uploaden tot FCM-MP3 folder omdat ik geen rechten op die heb.

**Comment by Area348** [comment]
????
Moet je die bestanden niet gewoon in de app meesturen?

**Comment by Area348** [comment]
Dit is wat de documentatie van FCM er overzicht:
Parameter: Sound
Usage: Optional, string
Desctoption:	
Indicates a sound to play when the device receives a notification. Supports default or the filename of a sound resource bundled in the app. Sound files must reside in /res/raw/.

Neem dat aan dat je de mp3's gewoon in de res/raw folder moet gooien?

**Comment by njittam** [comment]
die eerste vind ik ook leuk als is pokemon altijd goed.

**Comment by Dingenis** [comment]
@Area348 Klopt, maar zodat jij een preview kan geven. En dat we voor de goede orde de mp3s ook in de drive hebben.

**Comment by njittam** [comment]
Je bedoelt in drive?

**Comment by Dingenis** [comment]
Jupp, onder Jotihunt API -> V2 - > FCM-MP3

**Comment by Area348** [comment]
@Dingenis, sorry snap je zin niet.... Concreet wat moet ik er nog voor doen?

> @Area348 Klopt, maar zodat jij een preview kan geven. En dat we voor de goede orde de mp3s ook in de drive hebben.

**Comment by Dingenis** [comment]
Japp heeft nu geluiden voor de (FCM) notificaties sinds commit 9b94feb9a5649f7f6e48bc0f5ca8114e0d13416e. Je kunt ze [hier](https://github.com/RSDT/Japp/tree/master/app/src/main/res/raw) bekijken. De exacte naam van het geluid zonder de extensie moet onder de sound eigenschap komen in de body. Dus bijvoorbeeld "sound" : "modern_lvl_up"

**Comment by Area348** [comment]
Ja werkt, heb er 1 gekozen die nu als geluid ingesteld staat.
Zat nog heel even te denken om een 'brammetje' te doen, en voor david shaco als geluid in te stellen, maar das iets te lang bedacht ik^^
