### ISSUE TITLE
FCM TOKEN

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#37]
FCM token wordt niet geupdate als je de gegevens van de app verwijderd / opnieuwe in logt..

Nu ik een nieuw toestel heb was ik met beide ingelogd. maar de messages kwamen nog op de oude mob binnen (ook na omloggen naar test).

**Comment by Dingenis** [comment]
Duplicate of [#39](https://github.com/RSDT/Japp/issues/39)
