### ISSUE TITLE
FCM - Afzender

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#40]
FCM stuurt nu geen afzender mee.
Ergens in het bericht een afzender mee sturen?

Als het kan in app via aparte tag, zo dat in een klein lettertype onderaan de afzender kan staan.

```
----------------
|  Title       |
----------------
|              |
| Body         |
|              |
---------------
|         Afz. |
---------------
```

Als dit niet kan, een auto compleet met afz. $user$.

**Comment by Dingenis** [comment]
Kan helaas niet, een auto complete met afz. {USER} zou dan inderdaad het beste zijn :+1:

**Comment by Area348** [comment]
Prima ga ik daar volgende week mee aan de slag.

Ondersteunt FCM tekst opmaak? en zo ja welke?
<b><i><font><h1><em> [u] [i] [b] ???

**Comment by Dingenis** [comment]
FCM zorgt er alleen voor dat de berichten ontvangen worden en worden gepost als notificaties. Het zijn dus nog steeds Android Notificaties en die ondersteunen helaas geen tekst opmaak. De mogelijke opties die we voor de Notificatie kunnen zetten zijn [hier](https://firebase.google.com/docs/cloud-messaging/http-server-ref#table2) te vinden.

**Comment by Area348** [comment]
Helaas, maar het zij zo.

**Comment by Area348** [comment]
Poging gedaan om afzender er bij te zetten, helaas kan ik het momenteel niet testen omdat FCM het niet lijkt te doen, althans er komt niet binnen bij mij...

**Comment by Dingenis** [comment]
Sinds de fix van #39 in Japp 1.9.1 lijkt afzender te werken.  
![image](https://cloud.githubusercontent.com/assets/10774089/18924622/1ff81540-85b1-11e6-9b3b-269dcd72e0f5.png)
