### ISSUE TITLE
iconen moeten kleiner

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp#45]

**Comment by Area348** [comment]
Wel mee eens, ook al heb ik het idee dat de icon's nu wel goed schalen.
Van mij zouden de vossen icon's een schaal of 1-2 kleiner mogen.

**Comment by njittam** [comment]
ik heb even gekeken maar ik kan nergens de iconen vinden waar staan ze?

**Comment by njittam** [comment]
ze staan nl ook niet in de .gitignore

**Comment by Dingenis** [comment]
Gedeeltelijk gefixt in commit 2e6f7e69c4dd066b71c8b651d35f8b4cd39d5764 voor de vossen, er zal eerst nog getest moeten worden om het perfecte balans te vinden. In Japp 2.0.0 zal het testen beginnen.

**Comment by njittam** [comment]
de iconen zijn nu goed alleen de vossen mogen iets kleiner

**Comment by Dingenis** [comment]
Vanaf Japp 1.2.2 zijn de iconen ongeveer de juiste grootte
