### ISSUE TITLE
JAPP onthoud de instellingen

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#46]
Japp onthoud de instellingen TE goed.
Relog naar ander account onthoud de instelingen bv. Huntnaam van ander accound....

**Comment by Dingenis** [comment]
Klopt in Japp 1.9 zal hij alle gegevens van een gebruiker wissen(ook de FCM token #39). Maar is het niet handig om een paar instellingen te behouden, of is dit niet handig?

**Comment by njittam** [comment]
Je zou settings naar de server kunnen pushen. Of een losse settingsfile pp maken. Maar dan moet je ook een mogelijk

**Comment by njittam** [comment]
Kunnen maken om die bestanden te verwijderen

**Comment by Dingenis** [comment]
Waarom zouden de bestanden ook moeten verwijderd worden als je uitlogt? De bestanden bevatten alleen offline data zodat als er geen internet is dat je iets kan laten zien. Als je alle bestanden weg wilt kun je de Verse Start functie gebruiken in de instellingen onder het kopje Debug.

**Comment by Area348** [comment]
Niet alle data hoeft weg van mij.
Alleen account bound data.
Username,huntnaam,fcm-token,sleutel,dat wat ik nu nog vergeten ben.

**Comment by Dingenis** [comment]
In Japp 1.9.1 zullen de volgende gegevens worden weggegooid
- Gebruikersnaam
- Rank
- Id
- Naam
- Achternaam
- Email
- Datum Lid sinds
- Datum Laaste bezoek
- Actief Account
- Locatie van Avatar op de server
- Avatar
- FCM token
- Sleutel(API-key voor area348)
