### ISSUE TITLE
niet uit plaats marker kunnen komen.

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp#51]
Als je op (+) -> marker -> klaar klikt. blijf je markers neezetten en is het + menu weg. Het gaat wel goed met wegsliden

**Comment by Dingenis** [comment]
Ik kan de bug niet herproduceren. Krijg je als je op klaar klikt ook geen dialoog waar je gegevens kan invoeren?

**Comment by njittam** [comment]
nope
exact als bij de vorige bug met spot hunt marker.
 het is alleen bij de normale marker niet bij de spot of hunt marker

**Comment by Dingenis** [comment]
Inderdaad dezelfde bug als in #41, in Japp 1.9.2 zal dit werken vanaf commit 09cdda472e5399507d19a53ceb169904d06402b9
