### ISSUE TITLE
#41 all over again

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp#54]
je kunt nog steeds vastzitten in een hunt/ spot sessie. zoals in #41 en #51
(+) ->hunt/spot -> zet marker op de kaart -> klaar-> heel snel voor de popup verschijnt op een ander marker klikken -> je zit vast.

**Comment by njittam** [comment]
kom er net achter dat het niet perse een marker hoeft te zijn waar je op moet klikken kan ook een random andere plek zijn.

**Comment by Dingenis** [comment]
Wanneer je snel ergens anders klikt wordt de animatie onderbroken, en wordt de onFinish() nooit geroepen. Vanaf commit 75c7633b5fd62e5e1cd7f60ec60317ae22cab777 zal deze bug gefixt zijn. In de opkomende release Japp 2.1.1 zal dit werken.
