### ISSUE TITLE
Scouting groepen update??

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#55]
Net alle scouting groepen uit de DB gehaald, en dit doet hij niet op de kaart in de app updaten...
ook niet met een manual update.

Waarschijnlijk doet een data drup van de app wel de nieuwe data binnen halen (niet getest).

**Comment by njittam** [comment]
na een gegevens wissen doet ie t well

**Comment by Area348** [comment]
FCM stuurt nu:
topic: SC/update
message: 'SC'
Als het anders moet hoor ik het graag.
(update zelf nog in progress, edit werkt al).

**Comment by Area348** [comment]
Update zelf werkt nu ook.
Nog nog de individuele versie maken.

**Comment by Area348** [comment]
Individueel werkt nu ook :D

**Comment by Dingenis** [comment]
Paste ook in het systeem :) in Japp 2.0.0 zal het werken
