### ISSUE TITLE
Programma om notificaties te sturen naar gebruikers van Japp

### ISSUE THREAD

**Issue by Dingenis** [RSDT/Japp#6]
We zouden een programma kunnen maken wat notificaties kan laten zien op apparaten via FCM. Je zou dan bijvoorbeeld een message kunnen sturen naar iedereen in Deelgebied Alpha. Dit is misschien overdreven omdat we ook Telegram hebben. En voordeel van deze manier is dat Japp weet ik welk deelgebied je bent en daarom de thuisploeg niet hoeft bij te houden wie in welke groep zit.

**Comment by Dingenis** [comment]
Een specifieke user krijgt een token van FCM waarmee hij bereikbaar is, die token moet ik dan naar jou sturen. En jij zet hem in de db bij de bijhorende user zoals roan. Je kunt dan in db op naam roan zoeken en daarvan de token gebruiken om naar roan een message te zenden. De token in de db moet geupdate kunnen worden via de API omdat de token verandert.

**Comment by Area348** [comment]
Ik heb als het goed is een webpagina hiervoor klaar.
Geen id of het werk, aangezien ik niet kan zien of er iets binnen komt of niet.

Ook moet ik nog Tokens in de db krijgen hier voor, test heeft momenteel een test token van 123^^.


Webpagina: http://jotihunt2016.area348.nl/fcm_send_message.php
!!! App eerst Tokens laten sturen !!!
!!! Je kunt zien of er tokens binnen komen, als er meer gebruikers verschijnen in de dropdown ;) !!!

**Comment by Dingenis** [comment]
Ik heb de documentatie van FCM geupdate in de Google Drive map, hierin staat beschreven hoe we waarschijnlijk het beste de FCM message kunnen opbouwen.

**Comment by Area348** [comment]
Helemaal goed, ik ben de FCM-TextMessage al aan het aanpassen. 
Hoe gaan we icons afspreken, en door geven, namen/id's?!?!?!?

**Comment by Dingenis** [comment]
We kunnen voor de iconen een paar nemen als standaard bijvoorbeeld:
-  [Info](https://design.google.com/icons/#ic_info)
- [Belangerijk](https://design.google.com/icons/#ic_priority_high)
- En eventueel meer

Hoe bedoel je met namen/ids? :)

**Comment by Area348** [comment]
Okee alles is nu geimplementeerd :tada:.
Alleen nog een icon list die gebruikt kan/mag worden, maar dat staat in een var bestand ;).
Dus als je het voor elkaar krijg om FCM tokens naar de db te sturen dan kun je testen va. de website :smiley:

**Comment by Area348** [comment]
FF gekeken van wat ik terug krijg, en ik denk dat hij het doet naar FCM servers toe. Krijg namelijk een error dat er niemand geregistreerd is met dit id ;)....

{"multicast_id":8376890751947157898,"success":0,"failure":1,"canonical_ids":0,"results":[{"error":"InvalidRegistration"}]}

**Comment by Area348** [comment]
oo lol ik zie nu pas dankzij de mail dat je hier boven al gereageerd had.

met namen/id's bedoelde ik dus welke icons gaan we gebruiken, en hoe gaan we ze noemen.
Info/Belangrijk/etc. vindt ik prima, zijn dit zelf te maken icons, of standaard android icons?

**Comment by Area348** [comment]
Dit is nu werkend, zie meer FCM enchantment wensen bij de issues ;)
