### ISSUE TITLE
Vossen hebben geen groeiende cirkels?

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp#61]
Of hebben ze dezelde kleur

**Comment by Dingenis** [comment]
Heb je Automatische Cirkelvergroting aan staan?(Instellingen ->Extra ->Geavanceerd -> Automatiek)

**Comment by Dingenis** [comment]
Gefixt in commit 5d32416eadd62aa29100bc3dc6b5c790b2ee3907, in Japp 2.0.1 zal dit naar behoren werken
