### ISSUE TITLE
Vos cirkels alleen laatste

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#66]
Van mij mag de groei cirkel alleen bij de laatste locatie getoont worden als je hem aan klikt.

Nu krijg je bij alles minder dan een uur oud een groei cirkel

**Comment by njittam** [comment]
Ik vermoed dat dit bes

**Comment by njittam** [comment]
Lastig te veranderen is zo kort op de jh

**Comment by njittam** [comment]
I was wrong hoor ik bram is er mee bezig

**Comment by Dingenis** [comment]
In Japp 2.1 is dit geïmplementeerd, sinds commit  e2c437d0371aea04d6c872ba16151747d5916594.
