### ISSUE TITLE
In en uitzoom knop

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp#67]
Evt onderin de in en uitzoom knopen van google toevoegen.
GoogleMap.getUiSettings().setZoomControlsEnabled(true);

**Comment by Dingenis** [comment]
Ik zou een instelling hier voor kunnen maken, zoiets als "Zoom Paneel". Zodat mensen zelf kunnen bepalen of ze het willen hebben. Dit kan trouwens ook voor de andere mogelijke UiSettings controls

**Comment by Dingenis** [comment]
Vanaf Japp 2.1 hebben gebruikers zelf de mogelijkheid om map controls aan en uit te zetten(onder Instellingen -> Kaart -> Gereedschappen), sinds commit 13e6525839b2fc1ec8b00f93c7e1e1c7d593dee6

**Comment by Area348** [comment]
Is de schaalbar ook mogelijk?

**Comment by Dingenis** [comment]
Nee alleen [deze](https://developers.google.com/maps/documentation/android-api/controls) gereedschappen zijn mogelijk
