### ISSUE TITLE
Cirkel te groot

### ISSUE THREAD

**Issue by Area348** [RSDT/Japp#69]
Ik klikbergenscrandom om en krijg eenietsiepietsie grote cirkel
![screenshot_20161009-172634](https://cloud.githubusercontent.com/assets/14966999/19221549/d2c0c55e-8e45-11e6-8bed-6b139c298a91.png)

![screenshot_20161009-173010](https://cloud.githubusercontent.com/assets/14966999/19221577/5056868e-8e46-11e6-879f-1d31d97f1865.png)

**Comment by Dingenis** [comment]
De cirkel hoort zo groot te zijn, omdat de vos locatie al zo oud is(2016-10-07 15:34:24). In de aankomende update zal dit geen probleem meer zijn omdat hij dan alleen de cirkels laat zien van vos locaties minder oud dan 2 uur.

**Comment by Area348** [comment]
Mag van mij ook 1-1,5 uur worden.
Zo iets is ook op de site in gesteld, anders vervagen op een gegeven moment de kleuren van de kaart een btj.

**Comment by Dingenis** [comment]
In Japp 2.1 kan dit niet meer gebeuren sinds commit e2c437d0371aea04d6c872ba16151747d5916594
