### ISSUE TITLE
API Call om te checken of een API key nog wel geldig is

### ISSUE THREAD

**Issue by Dingenis** [RSDT/Japp#7]
Een call in de API waarmee je de sleutel opgeeft, en terug krijgt of de sleutel nog geldig is. Hiermee kan de app checken of de gebruiker nog wel ingelogd is tijdens het SplashScreen.

**Comment by Area348** [comment]
**API call aangemaakt:**

HTTP METHOD: GET
URL: /gebruiker/SLEUTEL/sleutelExcists
CONTENT: -
NOTE: 

RESPONSE: 
{
		
	"exists":			true
}

**Comment by Dingenis** [comment]
Typo in de url "Excists" ipv "exists"

**Comment by Area348** [comment]
Fixed hoop ik (ik zie dat echt niet^^)

**Comment by Dingenis** [comment]
Wanneer je een key gebruikt die niet geldig is, geeft de api een 401 error ipv exists : false

**Comment by Area348** [comment]
Klopt, Workting as intended.
