### ISSUE TITLE
Home Window

### ISSUE THREAD

**Issue by njittam** [RSDT/Japp#72]
misschien een leuke text?
of gwn verwijderen?

**Comment by Dingenis** [comment]
Ik kan via de Jotihunt API nieuws ophalen en dat daar weergeven, maar ik weet niet of dat handig is?

**Comment by Area348** [comment]
Misschien handig om daar de stoplichten op te zetten?

**Comment by Dingenis** [comment]
In Japp 2.1.3 wordt de home pagina gebruikt voor de status van de vossen.
